// CSS!
import './css/style.css';
import './css/navbar.css';
import './css/hero.css';
import './css/story.css';
import './css/dining.css';
import './css/news.css';
import './css/footer.css';
// JAVASCRIPTS!
import './js/main.js';