// CSS!
import './css/style.css';
import './css/navbar.css';
import './css/hero.css';
import './css/story.css';
import './css/dining.css';
import './css/news.css';
import './css/footer.css';
import './css/product-menu.css';
import './css/contact.css';
// JAVASCRIPTS!
import './js/fetch.js';
import './js/nav-menu.js';
import './js/menu.js';
import './js/dining-card.js';
import './js/main.js';
import './js/menuItem.js';
import './js/contact-form.js';